USE EMPLOY;
CREATE TABLE CUSTOMER(CUSTOMER_ID INT(10)NOT NULL,FIRST_NAME VARCHAR(20)NOT NULL,
LAST_NAME VARCHAR(20)NOT NULL,CITY VARCHAR(20)NOT NULL, PURACHASE_AMOUNT INT(10)NOT NULL,
PRIMARY KEY (CUSTOMER_ID));
SELECT*FROM CUSTOMER;
INSERT INTO CUSTOMER(CUSTOMER_ID,FIRST_NAME,LAST_NAME,CITY,PURACHASE_AMOUNT) VALUE(101,"RIYA","RAJ","pala",1500.789),
(102,"TINA",'MERIL',"cheery",29800.36),(103,"BENNY","SAM","kollam",15000.45),(104,"PARVATHY","CHANDRA",'uduppi',1200.34),
(105,"LEKSHMI","SAJAN",'thiruva',200000.36);
SELECT * FROM CUSTOMER;
ALTER TABLE CUSTOMER RENAME COLUMN PURACHASE_AMOUNT TO PURCHASE_AMOUNT;
#1) FIND THE NO:OF CHARACTERS IN THE FIRSTNAME OF EACH COLUMN
SELECT * FROM CUSTOMER;
USE EMPLOY;
SELECT * FROM CUSTOMER;
SELECT FIRST_NAME,CHAR_LENGTH(FIRST_NAME) AS LENG FROM CUSTOMER;
#2)COMBINE FIRST NAME AND LAST NAME IN SINGLE COLUMN
SELECT CONCAT(FIRST_NAME,'-',LAST_NAME) AS FL_NAME FROM CUSTOMER;
#3) FORMAT THE PURCAHSE AMOUNT TO TWO DECIMAL PLACES
SELECT FORMAT (PURCHASE_AMOUNT,2) AS DECIMAL1 FROM CUSTOMER;
#4)CONVERT ALL CITY NAMES TO UPPERCASE
SELECT UPPER(CITY)AS UPPER FROM CUSTOMER;
#5)CONVERTBALL FIRST NAME TO LOWER CASE
SELECT LOWER(FIRST_NAME)AS LOWER FROM CUSTOMER;
#6)REVERSE THE FIRST NAME OF EACH CUSTOMER
SELECT REVERSE(FIRST_NAME)AS REVERSE FROM CUSTOMER;
#7)Repeat the first letter of the first_name 3 times
SELECT FIRST_NAME,REPEAT(LEFT(FIRST_NAME,1),3) AS REPEAT_LTR FROM CUSTOMER;
#8)Extract the first 3 characters of the last_name
SELECT LEFT(LAST_NAME,3)AS LE FROM CUSTOMER;
#9)Extract the last 2 characters of the city
SELECT RIGHT(CITY,2)AS RT FROM CUSTOMER;
#10)Find the length of last_name in bytes 
SELECT LENGTH(LAST_NAME)AS LENG FROM CUSTOMER;