USE FULL_DATA;
CREATE TABLE DEPARTMENTS(DEP_ID CHAR(2)NOT NULL,DEP_NAME VARCHAR(20)NOT NULL, PRIMARY KEY (DEP_ID));
SELECT* FROM DEPARTMENTS;
CREATE TABLE EMPLOYEES(EMP_ID INT(10)NOT NULL,EMP_NAME VARCHAR(20)NOT NULL,DEP_ID CHAR(2)NOT NULL,
PRIMARY KEY (EMP_ID),FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENTS(DEP_ID));
SELECT * FROM EMPLOYEES;
INSERT DEPARTMENTS (DEP_ID,DEP_NAME)VALUE("SC","SCIENCE"),("EG","ENGLISH"),("MT","MATHEMATICS");
SELECT* FROM DEPARTMENTS;
INSERT EMPLOYEES(EMP_ID,EMP_NAME,DEP_ID)VALUE(101,"SADHU","SC"),(103,"REMA","EG"),(104,"MADHU","MT");
SELECT* FROM EMPLOYEES;
#INNER JOIN
USE FULL_DATA;
SELECT * FROM DEPARTMENTS INNER JOIN EMPLOYEES ON DEPARTMENTS.DEP_ID = EMPLOYEES.DEP_ID
#2)ADD NEW COLUMN
USE FULL_DATA;
ALTER TABLE EMPLOYEES ADD HIRE_DATE DATE;
SELECT * FROM EMPLOYEES;
#CHANGE COLUMN NAME
USE FULL_DATA;
ALTER TABLE EMPLOYEES CHANGE EMP_NAME  EMPLOYEE_NAME VARCHAR(20);
SELECT*FROM EMPLOYEES;
ALTER TABLE EMPLOYEES RENAME COLUMN EMP_ID TO EMPLOYEE_ID;
SELECT * FROM EMPLOYEES;
#4) DELETE UNWANTED COLUMN
USE FULL_DATA;
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES
DROP COLUMN HIRE_DATE;
SELECT * FROM EMPLOYEES;