#CREATE DATABASE
# CREATE TABLE
USE EMPLOY;
CREATE TABLE TECH(ID INT(10) NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, PROFESSION VARCHAR(30) NOT NULL, SALARY INT(10) NOT NULL, PRIMARY KEY (ID));
INSERT INTO TECH (ID,EMP_NAME,PROFESSION,SALARY) VALUE (101,"SARA","TUTOR","40000"),
(102,"RAHA","ANALYST","45000"),(103,"SOHAN","CREATOR","30000");
SELECT * FROM TECH;
# ADD COLUMN
USE EMPLOY;
ALTER TABLE TECH ADD PLACE VARCHAR(20) NOT NULL;
SELECT * FROM TECH;
#RENAME COLUMN
USE EMPLOY;
ALTER TABLE TECH RENAME COLUMN PLACE TO AGE;
SELECT * FROM TECH; 
USE EMPLOY;
UPDATE TECH SET AGE = 23 WHERE ID = 101;
SELECT * FROM TECH;
USE EMPLOY;
UPDATE TECH SET AGE = 24 WHERE ID = 102;
UPDATE TECH SET AGE = 21 WHERE ID = 103;
SELECT * FROM TECH;
#DROP COLUMN
USE EMPLOY;
ALTER TABLE TECH DROP COLUMN AGE;
SELECT * FROM TECH;
# RENAME TABLE
USE EMPLOY;
ALTER TABLE TECH RENAME TO TECHNO;
SELECT * FROM TECHNO;



